# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target :PWProgressViewTests, :exclusive => true do
	pod 'Kiwi'
end

target 'PWProgressView iOS Tests' do
	pod 'Kiwi'
end
